# Use generic build mode on Ubuntu
image: Ubuntu
build: off

# Test against the latest version of this Node.js version
environment:
  nodejs_version: '16'

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - nvm use 16
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
